title: It's Our Mission
description: >-
  It's Our Mission is an open-source Nonprofit Tech project set to help Nonprofit Techs see what others are building in our space.
baseurl: ""
url: ""

permalink: /:title/


# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-sitemap
  - jekyll-assets
  - uglifier
  - autoprefixer-rails
  - sprockets
  - jekyll-paginate-v2

includes:
  - _pages
  - about_us
  - contact_us
  - _nptechs


# SASS Settings
sass:
  sass_dir: _sass
  style: compressed

assets:
  digest: false
  cache: false
  compression: false
  source_maps: false
  dirname: "assets"
  prefix: "/assets"
  sources:
    - _assets/css
    - _assets/docs
    - _assets/img
    - _assets/js
    - _assets/pdf
  compress:
    css:  sass
    js:   uglifier


# Collections
collections:
  nptechs:
    output: true
    permalink: /nptechs/:slug/


# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata
  - hydra-validate
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
